"""empty message

Revision ID: 336b421c25e2
Revises: 59e1ebdf3ad8
Create Date: 2021-02-26 20:36:16.304956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '336b421c25e2'
down_revision = '59e1ebdf3ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('rotation_period', sa.String(length=80), nullable=True))
    op.drop_column('planets', 'rotataion_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('rotataion_period', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('planets', 'rotation_period')
    # ### end Alembic commands ###
